### ISSUE TITLE
Installation via pip broken due to missing __init__.py

### ISSUE THREAD

**Issue by LukasSchulz** [pretalx/pretalx-public-voting#25]
I have struggled to install the updated version of the plugin using pip for a while now and found the problem today:

In the setup.py the packages to be installed are found using `find_packages()` from `setuptools`, which seems to be the preferred version of doing things, but returns an empty list, when there is no `__inity__.py` present in the module folder. Simply adding an empty file named `__init__.py` in the module folder resolved the issue for me.
References:
https://github.com/pretalx/pretalx-public-voting/blob/b908b61992b94b9c3312221431e399e9fd3e291d/setup.py#L35
https://stackoverflow.com/a/64404115

**Comment by rixx** [comment]
Added file, released v1.2.2
