### ISSUE TITLE
Public voting for already confirmed sessions

### ISSUE THREAD

**Issue by dionzand** [pretalx/pretalx-public-voting#34]
Hi,

I think my wish is not where this plugin was intended to be used for, but I would like to use the public voting tool for voting for the best talk. The conference we are organizing is a competition and we want the audience to vote for the best talk. However, the plugin now only displays new submissions. Can the tool also be used on confirmed sessions?

Thanks!
Kind regards,
Dion

**Comment by rixx** [comment]
This plugin is only intended to vote on new proposals, and doesn't have functionality for voting on confirmed proposals. I'd think that the pretalx built-in feedback functionality would be a better fit for that.
