### ISSUE TITLE
After plugin installation this doesn't apper in event settings.

### ISSUE THREAD

**Issue by LanusseMorais** [pretalx/pretalx-public-voting#35]
I have a self-hosted instance and installed this plugin inside Venv using pip. I rebuild the pretalx and restart services, but although plugins appear on admin page this doesn't appear in the events settings to enable. Do you know what I'm doing wrong?

Commands used to install:
```shell
(venv) pretalx@pretlax:~$ pip install pretalx_public_voting
(venv) pretalx@pretlax:~$ python -m pretalx makemigrations
(venv) pretalx@pretlax:~$ python -m pretalx migrate
(venv) pretalx@pretlax:~$ python -m pretalx rebuild --npm-install
(venv) pretalx@pretlax:~$ python -m pretalx regenerate_css
root@pretlax:~# systemctl restart  pretalx-web pretalx-worker nginx redis
```
Admin page
![image](https://github.com/user-attachments/assets/6a64a596-be1d-4c5c-ad19-313449df2251)
Demo event page
![image](https://github.com/user-attachments/assets/2435e68f-9a5d-46ef-84d4-7cd25ef28b3d)

**Comment by rixx** [comment]
That's a bug in pretalx v2024.2.0 – oops.

I just released v2024.2.1, which will make plugins show up again. Thanks for opening this bug report!
