### ISSUE TITLE
Grayed out "Save!" button is confusing

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx-public-voting#9]
I was confused by the grayed out "Save!" button at the bottom.

I then got the idea that it is used if JS isn't enabled (which is really a great idea to solve it like this). Though perhaps we can change how things are presented if JS is enabled.

One idea I had was that perhaps the spinner next to the "Save!" button (when you just selected a talk) could change to something like "autosave complete" or so if it was saved. And then become a spinner again if you cast a vote.

**Comment by rixx** [comment]
This plugin isn't really in a usable state at the moment – there's currently no good way to get any evaluation of the votes, and even the frontend isn't quite there yet.

**Comment by vmx** [comment]
Yes. But I want to get it into a usable state :)
